
//匹配路由标题
export default {
    '/': '消防督查',
    '/AccountChoose': '职位选择',
    '/Main': '消防督查',
    '/SearchAround': '搜索周边',
    '/TroubleFix': '隐患整改统计',
    '/FixInfo': '单位整改情况',
    '/FixDetail': '整改详情',
    '/ChecksDetail': '记录详情',
    '/UnitCheck': '单位检查',
    '/CheckTypes': '检查类型',
    '/PatrolRecord': '巡查记录查询',
    '/PatrolDetail': '巡查记录明细',
    '/PswUpdate':'密码修改',
    '/ReFix':'重新整改',
    '/PassFix': '通过',
    '/SearchPage': '请搜索',
    '/UnitCheckTypes': '检查模板选择',
    '/Login': '登陆',
    '/Around': '周边',
    '/Myself': '我的',
    '/DemoList': '测试',
    '/ProjectDetail': '项目详情',
    '/ScorePart': '单位得分',
    '/RankPart': '单位排名',
    '/HistoryInfo': '单位历史消息',
    '/WirelessAlarmList': '无线报警系统',
    '/GridManPatrols': '网格员巡查历史记录',
    '/DeviceSetupInfo': '设备安装信息',
    '/DeviceDetail': '设备明细',
    '/Parts': '单位维护',
    '/PartHandle': '单位新增',
    '/RecordFire': '火警记录',
    '/FireDetail': '火警记录详情页',
    '/RescueIn': '火警记录录入',
    '/AreaFilter': '区域选择',
    '/EntityDetail': '详情',
    '/PartPatrolRecrod': '单位巡查记录',
    '/PartElecsys': '点击火灾监控系统',
    '/ElecStatusList': '电力设施状态列表',
    '/SysPatrolDayDetail': '巡查详情',
    '/MyWork':'我的工作情况',
    '/MyChecks':'我的检查情况',
    '/MyHiddenTroubles':'我的隐患整改',
    '/PatrolDetailSelf': '检查记录清单'
}